apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-nfs-deployment
  namespace: test-nfs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-nfs-deployment
  template:
    metadata:
      labels:
        app: test-nfs-deployment
    spec:
      containers:
      - name: test-nfs-deployment
        image: nginx:latest
        imagePullPolicy: Always
        lifecycle:
          postStart:
            exec:
              command: ["/bin/bash", "-c", "echo 'mounted nfs path is /mnt/test-nfs ' > /usr/share/nginx/html/index.html"]
        volumeMounts:
        - mountPath: "/mnt/test-nfs"
          name: nfs-pvc-test
      volumes:
        - name: nfs-pvc-test
          persistentVolumeClaim:
            claimName: nfs-pvc