apiVersion: v1
kind: Service
metadata:
  name: rolling-service
  namespace: rolling-update
  labels:
    app: rolling-deployment
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    name: http
  selector:
    app: rolling-deployment