apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
  namespace: persistent-disk-test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: simple-disk