apiVersion: apps/v1
kind: Deployment
metadata:
  name: readiness-deployment
  namespace: readiness-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: readiness-deployment
  template:
    metadata:
      labels:
        app: readiness-deployment
    spec:
      containers:
      - name: readiness-deployment
        image: kubernetespractice/kubernetes-practice:delay-60
        # image: nginx:latest
        # imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10