apiVersion: v1
kind: Service
metadata:
  name: readiness-service
  namespace: readiness-namespace
  labels:
    app: readiness-deployment
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    name: http
  selector:
    app: readiness-deployment