apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv2-nfs
  namespace: test-nfs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  nfs:
    path: /mnt/nfs2
    server: 1.1.1.1