apiVersion: v1
kind: Service
metadata:
  name: test-nfs-service2
  namespace: test-nfs
  labels:
    app: test-nfs-deployment2
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    name: http
  selector:
    app: test-nfs-deployment2